### PR TITLE
#36: sepa account balances 

### LINKED ISSUE #36: AccountBalances V7
Hi,
   
I just tried to fetch AccountBalances from a bank and got:
   
`unsupported versions [7 4]`
   
A bit of searching in the code showed that only version 5 and 6 are supported for now:
   
https://github.com/mitch000001/go-hbci/blob/4ea2bd4bc4404b562471b1876983467821e3c024/segment/account_balance.go#L12
   
Then checked:
   
https://github.com/raphaelm/python-fints/blob/eb94706a9ba9f91f69e3e734abe8d4e746ea82b8/fints/segments/saldo.py#L67
   
and it seems AccountConnectionDataElement changed from "Kontoverbindung, version 2" to "Kontoverbindung international, version 1" according to python-fints. The Gesamtdok_HBCI22.pdf however shows in II 5.3.3 the same structure implemented in go-hbci.
   
If I'm not mistaken the data structure in V7 also includes IBAN and BIC:
   
https://github.com/raphaelm/python-fints/blob/eb94706a9ba9f91f69e3e734abe8d4e746ea82b8/fints/formals.py#L476
   
I then tried to follow the implementation of V7 in:
   
https://github.com/mitch000001/go-hbci/blob/4ea2bd4bc4404b562471b1876983467821e3c024/segment/account_transaction.go#L29                                                                                    
                                                                                                                
and got lost. Would AccountBalance also require a SepaAccountBalances?
   
Any hints are highly appreciated. Thanks!

### PR DESCRIPTION
**Pull request by mitch000001**
This PR introduces account balance segments in version 6, 7 and 8 (HKSAL) which allows clients which only support version 4 and earlier (non sepa) or version 7 or later (sepa) of that segment.

This fixes #36

### CODE REVIEW

**Comment by pmoscode** [comment]
I kindly want to ask, when this PR will be merged. I would like to use it in my application.

Thx and greetings

**Comment by mitch000001** [comment]
Hi @pmoscode , thanks for using this library and getting in touch. Currently it seems that for some bank institutes there are some errors due to some parts of this PR.
We're trying to resolve those and will go forward with merging this.

**Comment by pmoscode** [comment]
Great, that it is finally merged!
So I can start write a microservice for [Invoice Ninja](https://www.invoiceninja.com/) now.
Thanks again!

**Comment by mitch000001** [comment]
@pmoscode You're very welcome. Feel free to give feedback on your usage and you're always welcome to report bugs you find.

Best,
Michael

**Pull request merged**
